ci: set continue-on-error to false in pr-title-checker action (#496)
* ci: set continue-on-error to false in pr-title-checker action

Signed-off-by: Lin Yang <reaver@flomesh.io>

* feat: improve the workflow

Signed-off-by: Lin Yang <reaver@flomesh.io>

* feat: improve the workflow

Signed-off-by: Lin Yang <reaver@flomesh.io>

---------

Signed-off-by: Lin Yang <reaver@flomesh.io>

fix: a typo

Signed-off-by: Lin Yang <reaver@flomesh.io>

fix: executing condition of pr title workflow

Signed-off-by: Lin Yang <reaver@flomesh.io>

fix: executing condition of pr title workflow

Signed-off-by: Lin Yang <reaver@flomesh.io>

fix: workflow condition of checking pr title

Signed-off-by: Lin Yang <reaver@flomesh.io>

fix: workflow syntax

Signed-off-by: Lin Yang <reaver@flomesh.io>

diff --git a/.github/workflows/pr-title-check.yml b/.github/workflows/pr-title-check.yml
--- a/.github/workflows/pr-title-check.yml
+++ b/.github/workflows/pr-title-check.yml
@@ -22,19 +22,25 @@ jobs:
   validate:
     name: Validate PR Title
     runs-on: ubuntu-latest
+    outputs:
+      success: ${{ steps.check.outputs.success }}
     steps:
       - name: PR Title Check
         uses: thehanimo/pr-title-checker@v1.4.3
         id: check
-        continue-on-error: true
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           pass_on_octokit_error: false
           configuration_path: ".github/pr-title-checker-config.json"
 
+  fail:
+    name: PR Title Check Failed
+    runs-on: ubuntu-latest
+    needs: validate
+    if: ${{ always() && needs.validate.outputs.success == 'false'}}
+    steps:
       - name: Add comment to fix PR title
         uses: marocchino/sticky-pull-request-comment@v2
-        if: ${{ steps.check.outputs.success == 'false'}}
         with:
           header: 'PR Title Check'
           recreate: true
@@ -47,15 +53,24 @@ jobs:
             * `feat: add new feature AB#789`
             * `chore: fixing build pipeline` - no AB reference
             * `build(deps): bump BlahBlah from 1.0 to 1.1`
-            * `[WIP] feat: add new feature AB#123`
-            * `[CHERRY-PICK] fix: fix typo in README.md AB#123`
-            * `[BACKPORT] fix: fix typo in README.md AB#123`
+            * `[wip] feat: add new feature AB#123`
+            * `[cherry-pick] fix: fix typo in README.md AB#123`
+            * `[backport] fix: fix typo in README.md AB#123`
             
             For more details, please refer to the [Conventional Commits Specification](https://www.conventionalcommits.org/en/v1.0.0)
             and the [PR Title Configuration File](.github/pr-title-checker-config.json).
+      - name: Set action status to failed
+        run: |
+          echo "❌ PR Title Check Failed"
+          exit 1
 
+  success:
+    name: PR Title Check Passed
+    runs-on: ubuntu-latest
+    needs: validate
+    if: ${{ always() && needs.validate.outputs.success == 'true' }}
+    steps:
       - name: Add comment that PR title is fixed
-        if: ${{ steps.check.outputs.success == 'true'}}
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           header: 'PR Title Check'
